CREATE TABLE `aluno` (
  `MATRICULAALUNO` int(11) NOT NULL,
  `DATANASCIMENTO` date DEFAULT NULL,
  `NOMEALUNO` varchar(50) DEFAULT NULL,
  `SEXOALUNO` char(1) DEFAULT NULL,
  `TELEFONE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`MATRICULAALUNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `curso` (
  `CODIGOCURSO` int(11) NOT NULL AUTO_INCREMENT,
  `NOMECURSO` varchar(50) DEFAULT NULL,
  `TIPOENSINO` varchar(10) DEFAULT NULL,
  `DURACAO` int(11) DEFAULT NULL,
  PRIMARY KEY (`CODIGOCURSO`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;


CREATE TABLE `disciplina` (
  `CODIGODISCIPLINA` int(11) NOT NULL AUTO_INCREMENT,
  `NOMEDISCIPLINA` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CODIGODISCIPLINA`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;


CREATE TABLE `disciplinaturma` (
  `CODIGODISCIPLINATURMA` int(11) NOT NULL AUTO_INCREMENT,
  `CODIGODISCIPLINA` int(11) NOT NULL,
  `CODIGOPROFESSOR` int(11) NOT NULL,
  `CODIGOTURMA` int(11) NOT NULL,
  `CODIGONOTA` int(11) NOT NULL,
  PRIMARY KEY (`CODIGODISCIPLINATURMA`),
  KEY `FK_DISCIPLINATURMA_DISCIPLINA` (`CODIGODISCIPLINA`),
  KEY `FK_DISCIPLINATURMA_NOTA` (`CODIGONOTA`),
  KEY `FK_DISCIPLINATURMA_PROFESSOR` (`CODIGOPROFESSOR`),
  KEY `FK_DISCIPLINATURMA_TURMA` (`CODIGOTURMA`),
  CONSTRAINT `FK_DISCIPLINATURMA_DISCIPLINA` FOREIGN KEY (`CODIGODISCIPLINA`) REFERENCES `disciplina` (`CODIGODISCIPLINA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_DISCIPLINATURMA_NOTA` FOREIGN KEY (`CODIGONOTA`) REFERENCES `nota` (`CODIGONOTA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_DISCIPLINATURMA_PROFESSOR` FOREIGN KEY (`CODIGOPROFESSOR`) REFERENCES `professor` (`CODIGOPROFESSOR`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_DISCIPLINATURMA_TURMA` FOREIGN KEY (`CODIGOTURMA`) REFERENCES `turma` (`CODIGOTURMA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;


CREATE TABLE `falta` (
  `MATRICULAALUNO` int(11) DEFAULT NULL,
  `CODIGODISCIPLINATURMA` int(11) DEFAULT NULL,
  `MES` varchar(15) DEFAULT NULL,
  `QTDFALTA` int(11) DEFAULT NULL,
  `ABONO` varchar(5) DEFAULT NULL,
  `MOTIVO` varchar(50) DEFAULT NULL,
  KEY `FK_FALTA_ALUNO` (`MATRICULAALUNO`),
  KEY `FK_FALTA_DISCIPLINA` (`CODIGODISCIPLINATURMA`),
  CONSTRAINT `FK_FALTA_ALUNO` FOREIGN KEY (`MATRICULAALUNO`) REFERENCES `aluno` (`MATRICULAALUNO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_FALTA_DISCIPLINA` FOREIGN KEY (`CODIGODISCIPLINATURMA`) REFERENCES `disciplinaturma` (`CODIGODISCIPLINATURMA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `frequencia` (
  `MATRICULAALUNO` int(11) DEFAULT NULL,
  `CODIGODISCIPLINATURMA` int(11) DEFAULT NULL,
  KEY `FK_FREQUENCIA_ALUNO` (`MATRICULAALUNO`),
  KEY `FK_FREQUENCIA_DISCIPLINATURMA` (`CODIGODISCIPLINATURMA`),
  CONSTRAINT `FK_FREQUENCIA_ALUNO` FOREIGN KEY (`MATRICULAALUNO`) REFERENCES `aluno` (`MATRICULAALUNO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_FREQUENCIA_DISCIPLINATURMA` FOREIGN KEY (`CODIGODISCIPLINATURMA`) REFERENCES `disciplinaturma` (`CODIGODISCIPLINATURMA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `grade` (
  `CODIGOGRADE` int(11) NOT NULL,
  `CODIGOCURSO` int(11) NOT NULL,
  `CODIGOPERIODO` int(11) NOT NULL,
  `CODIGODISCIPLINA` int(11) NOT NULL,
  PRIMARY KEY (`CODIGOGRADE`),
  KEY `FK_GRADE_CURSO` (`CODIGOCURSO`),
  KEY `FK_GRADE_PERIODO` (`CODIGOPERIODO`),
  KEY `FK_GRADE_DISCIPLINA` (`CODIGODISCIPLINA`),
  CONSTRAINT `FK_GRADE_CURSO` FOREIGN KEY (`CODIGOCURSO`) REFERENCES `curso` (`CODIGOCURSO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_GRADE_DISCIPLINA` FOREIGN KEY (`CODIGODISCIPLINA`) REFERENCES `disciplina` (`CODIGODISCIPLINA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_GRADE_PERIODO` FOREIGN KEY (`CODIGOPERIODO`) REFERENCES `periodo` (`CODIGOPERIODO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `nota` (
  `CODIGONOTA` int(11) NOT NULL AUTO_INCREMENT,
  `MATRICULAALUNO` int(11) NOT NULL,
  `RECUPERACAO` varchar(10) DEFAULT NULL,
  `FINAL` varchar(10) DEFAULT NULL,
  `TIPONOTA` varchar(10) DEFAULT NULL,
  `SITUACAO` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`CODIGONOTA`),
  KEY `FK_NOTA_ALUNO` (`MATRICULAALUNO`),
  CONSTRAINT `FK_NOTA_ALUNO` FOREIGN KEY (`MATRICULAALUNO`) REFERENCES `aluno` (`MATRICULAALUNO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `notaconceito` (
  `CODIGONOTA` int(11) NOT NULL,
  `CONCEITO1` varchar(10) DEFAULT NULL,
  `CONCEITO2` varchar(10) DEFAULT NULL,
  KEY `FK_NOTACONCEITO_NOTA` (`CODIGONOTA`),
  CONSTRAINT `FK_NOTACONCEITO_NOTA` FOREIGN KEY (`CODIGONOTA`) REFERENCES `nota` (`CODIGONOTA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `notanumero` (
  `CODIGONOTA` int(11) NOT NULL,
  `NOTA1` varchar(10) DEFAULT NULL,
  `NOTA2` varchar(10) DEFAULT NULL,
  KEY `FK_NOTANUMERO_NOTA` (`CODIGONOTA`),
  CONSTRAINT `FK_NOTANUMERO_NOTA` FOREIGN KEY (`CODIGONOTA`) REFERENCES `nota` (`CODIGONOTA`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `periodo` (
  `CODIGOPERIODO` int(11) NOT NULL AUTO_INCREMENT,
  `CODIGOCURSO` int(11) NOT NULL,
  `NUMEROPERIODO` int(11) DEFAULT NULL,
  PRIMARY KEY (`CODIGOPERIODO`),
  KEY `FK_PERIODO_CURSO_idx` (`CODIGOCURSO`),
  CONSTRAINT `FK_PERIODO_CURSO` FOREIGN KEY (`CODIGOCURSO`) REFERENCES `curso` (`CODIGOCURSO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

CREATE TABLE `professor` (
  `CODIGOPROFESSOR` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(50) DEFAULT NULL,
  `TELEFONE` varchar(15) DEFAULT NULL,
  PRIMARY KEY (`CODIGOPROFESSOR`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `professordisciplina` (
  `CODIGOPROFESSOR` int(11) DEFAULT NULL,
  `CODIGODISCIPLINA` int(11) DEFAULT NULL,
  `CODIGOPROFESSORDISCIPLINA` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`CODIGOPROFESSORDISCIPLINA`),
  KEY `FK_PROFESSORDISCIPLINA_DISCIPLINA` (`CODIGODISCIPLINA`),
  KEY `FK_PROFESSORDISCIPLINA_PROFESSOR` (`CODIGOPROFESSOR`),
  CONSTRAINT `FK_PROFESSORDISCIPLINA_DISCIPLINA` FOREIGN KEY (`CODIGODISCIPLINA`) REFERENCES `disciplina` (`CODIGODISCIPLINA`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_PROFESSORDISCIPLINA_PROFESSOR` FOREIGN KEY (`CODIGOPROFESSOR`) REFERENCES `professor` (`CODIGOPROFESSOR`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;

CREATE TABLE `sala` (
  `CODIGOSALA` int(11) NOT NULL AUTO_INCREMENT,
  `DESCRICAOSALA` varchar(10) DEFAULT NULL,
  `CAPACIDADE` int(11) DEFAULT NULL,
  PRIMARY KEY (`CODIGOSALA`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `tipousuario` (
  `CODIGOTIPOUSUARIO` int(11) NOT NULL,
  `DESCRICAOTIPOUSUARIO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`CODIGOTIPOUSUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `turma` (
  `CODIGOTURMA` int(11) NOT NULL AUTO_INCREMENT,
  `CODIGOPERIODO` int(11) DEFAULT NULL,
  `ANO` varchar(4) DEFAULT NULL,
  `TURNO` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`CODIGOTURMA`),
  KEY `FK_TURMA_PERIODO` (`CODIGOPERIODO`),
  CONSTRAINT `FK_TURMA_PERIODO` FOREIGN KEY (`CODIGOPERIODO`) REFERENCES `periodo` (`CODIGOPERIODO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `usuario` (
  `CODIGOUSUARIO` int(11) NOT NULL AUTO_INCREMENT,
  `CODIGOTIPOUSUARIO` int(11) NOT NULL,
  `USUARIOLOGIN` varchar(50) NOT NULL,
  `SENHA` int(11) NOT NULL,
  `CONFIRMARSENHA` int(11) NOT NULL,
  PRIMARY KEY (`CODIGOUSUARIO`),
  KEY `FK_USUARIO_TIPOUSUARIO` (`CODIGOTIPOUSUARIO`),
  CONSTRAINT `FK_USUARIO_TIPOUSUARIO` FOREIGN KEY (`CODIGOTIPOUSUARIO`) REFERENCES `tipousuario` (`CODIGOTIPOUSUARIO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
